version: "3.8"
services:
  db:
    restart: always
    image: postgres:13
    networks:
      - backend
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trustz
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    user: "${USERID}:${GROUPID}"
    volumes:
      - ./db:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.8-alpine
    networks:
      - backend

  web:
    build: .
    ports:
      - 8080:8080
    entrypoint: ./entrypoint.sh
    environment:
      - USERID=${USERID}
    user: "${USERID}:${GROUPID}"
    volumes:
      - .:/project
      - ./proj:/tmp/projects
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend
      - frontend

networks:
  frontend:
  backend:
    internal: true
