#!/bin/bash

cp sdaps_web/settings_sample.py sdaps_web/settings.py

echo "Building Docker image for sdaps_web"
sleep 1s

docker-compose build
docker-compose up -d

echo "Waiting for 20 seconds to let the containers start properly"
sleep 20s

echo "Running migrations"
sleep 1s
docker-compose exec web python manage.py migrate

echo "Running script to create the superuser"
sleep 1s
docker-compose exec web python manage.py createsuperuser --username "admin"

docker-compose down
