#!/bin/bash

set -e

echo "This will delete the whole database and all projects in your workspace."
echo "It also will reset your docker setup."
read -p "Are you sure you want to continue? [y/N]" yn
echo

if [[ $yn =~ ^[Yy]$ ]]
then
  echo "Resetting everything!"

  docker-compose down
  rm -rf node_modules db proj .env
  ./easy/init
fi
