# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 23:43
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import sdaps_ctl.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(db_index=True, max_length=10)),
                ('celeryid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locked', models.BooleanField(default=False)),
                ('initialized', models.BooleanField(default=False)),
                ('surveyid', models.PositiveIntegerField(default=0)),
                ('globalid', models.CharField(blank=True, default='', max_length=40)),
                ('title', models.CharField(default='', max_length=200)),
                ('author', models.CharField(default='', max_length=200)),
                ('questionnaire', models.TextField(default='[]')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('review_survey', 'Can review surveys'),),
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(editable=False, max_length=255, storage=django.core.files.storage.FileSystemStorage('/tmp/projects', base_url=None), upload_to=sdaps_ctl.models.UploadedFile.generate_filename)),
                ('filename', models.CharField(max_length=255)),
                ('filesize', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Uploading'), (1, 'Finished'), (2, 'Error')], default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='sdaps_ctl.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='scheduledtasks',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sdaps_ctl.Survey'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledtasks',
            unique_together=set([('survey', 'task')]),
        ),
    ]
