# Generated by Django 2.1.2 on 2018-10-07 15:43

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import sdaps_ctl.models


class Migration(migrations.Migration):

    dependencies = [
        ('sdaps_ctl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtasks',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='sdaps_ctl.Survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='questionnaire',
            field=models.BinaryField(default=b'[]'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(editable=False, max_length=255, storage=django.core.files.storage.FileSystemStorage('/home/dennis/Projekte/sdaps_web/proj', base_url=None), upload_to=sdaps_ctl.models.UploadedFile.generate_filename),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='sdaps_ctl.Survey'),
        ),
    ]
