# Generated by Django 2.1.2 on 2019-02-20 12:50

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    model = apps.get_model('sdaps_ctl', 'survey')
    for row in model.objects.all():
        row.slug = uuid.uuid4()
        row.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('sdaps_ctl', '0002_auto_20181015_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='survey',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
