# Generated by Django 2.1.2 on 2019-02-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdaps_ctl', '0002_auto_20181015_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='slug',
            field=models.SlugField(default='74dc9', unique=True),
        ),
    ]
