# Generated by Django 2.1.7 on 2019-02-27 14:48

import django.core.files.storage
from django.db import migrations, models
import sdaps_ctl.models


class Migration(migrations.Migration):

    dependencies = [
        ('sdaps_ctl', '0003_survey_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(editable=False, max_length=255, storage=django.core.files.storage.FileSystemStorage('/home/dennis/Downloads/sdaps_web/proj', base_url=None), upload_to=sdaps_ctl.models.UploadedFile.generate_filename),
        ),
    ]
