# Generated by Django 2.1.7 on 2019-07-07 21:50

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import sdaps_ctl.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sdaps_ctl', '0004_auto_20190227_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='group',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='owner',
        ),
        migrations.AddField(
            model_name='survey',
            name='owner',
            field=models.ManyToManyField(related_name='ownership_of_survey', related_query_name='ownership_of_survey', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(editable=False, max_length=255, storage=django.core.files.storage.FileSystemStorage('/tmp/projects', base_url=None), upload_to=sdaps_ctl.models.UploadedFile.generate_filename),
        ),
    ]
