# Generated by Django 2.1.7 on 2019-12-24 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdaps_ctl', '0006_auto_20190715_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('can_design_draft', 'Can design a survey draft via the editor'), ('can_initialize', 'Can finally setup/initialize the survey for printing'), ('can_download_empty', 'Can download empty (to be filled) survey)'), ('can_upload_scans', 'Can upload scanned sheets'), ('can_review_scans', 'Can review uploaded scanned sheets'), ('can_verify_scans', 'Can verify uploaded reviewed scans per page'), ('can_download_results', 'Can download report and csv files'), ('can_download_scans', 'Can download uploaded scanned sheets'), ('can_download_project', 'Can download the whole sdaps project for backup or working locally'), ('can_edit_basic_info', 'Can edit for example title, author, global id...'))},
        ),
    ]
