# Generated by Django 2.2.10 on 2020-05-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdaps_ctl', '0007_auto_20191224_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='language',
            field=models.CharField(default='', max_length=200),
        ),
    ]
