# Generated by Django 2.2.16 on 2020-10-26 21:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdaps_ctl', '0008_survey_language'),
    ]

    # https://stackoverflow.com/questions/56188275/converting-bytea-to-json
SELECT convert_from(decode(Survey.questionnaire, 'escape'),'UTF8')
SELECT convert_from(decode(Survey.questionnaire, 'escape'),'UTF8')::jsonb -> Survey.questionnaire


    operations = [
        migrations.RunSQL(
            "CREATE INDEX i_active_posts ON posts(id) WHERE active",
            "DROP INDEX i_active_posts"
        )
        migrations.AlterField(
            model_name='survey',
            name='questionnaire',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
