# Generated by Django 2.2.16 on 2020-10-25 17:55

import django.core.files.storage
from django.db import migrations, models
import sdaps_ctl.models


class Migration(migrations.Migration):

    dependencies = [
        ('sdaps_ctl', '0008_survey_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='latex_class_options',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(editable=False, max_length=255, storage=django.core.files.storage.FileSystemStorage('/home/dennis/projects', base_url=None), upload_to=sdaps_ctl.models.UploadedFile.generate_filename),
        ),
    ]
